src/components/atoms/index.ts, src/components/atoms/index.tsx
`src/components/atoms/` 直下の index ファイルが2つあり、エラーが発生していたので1つにまとめました。
`src/components/pages/PageTop/index.tsx` にて、 Button コンポーネントの import でエラーが発生している。
```zsh
❯ yarn build
yarn run v1.22.18
$ next build && next export
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
info  - Linting and checking validity of types ..Failed to compile.
./src/components/pages/PageTop/index.tsx:3:10
Type error: Module '"src/components/atoms"' has no exported member 'Button'.
1 | import { Box, Typography } from '@mui/material'
2 | import type { NextPage } from 'next'
> 3 | import { Button } from 'src/components/atoms'
|          ^
4 | import { Layout } from 'src/components/commons'
5 | import { useTranslation } from 'react-i18next'
6 | import { useRouter } from 'next/router'
> Build error …
```
=> [fix] Delete duplicated index file in `components/atoms/`

package.json, yarn.lock
`yarn lint` を実行すると以下のようなワーニングが出ていた
```
$ next lint
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0
YOUR TYPESCRIPT VERSION: 4.8.2
Please only submit bug reports when using the officially supported version.
=============
✔ No ESLint warnings or errors
Done in 2.14s.
```
パッケージのバージョンが一部古いので更新した
```
yarn upgrade next@12.3.1
yarn upgrade eslint-config-next@12.3.1
yarn
```
- [vercel/next - v12.2.5..v12.3.1](https://github.com/vercel/next.js/compare/v12.2.5..v12.3.1)
=> yarn upgrade(next, eslint-config-next)

.husky/pre-commit
* VS Codeで`git commit` しようとするとエラーが発生していたので、スクリプトを修正した
* ref: https://github.com/typicode/husky/issues/912#issuecomment-887840695
=> vs codeのgit機能が使えなくなっていたのでnpxのパスを通した

src/components/organisms/Footer/index.tsx
レンダリングされるHTMLの構造が、pタグの中にaタグが存在する書き方になっており、開発環境では警告が表示されていた
=> fix: footer

src/components/organisms/SpeakersSection/SpeakersSection.stories.tsx, src/components/organisms/SpeakersSection/index.tsx, src/components/organisms/SponsorsSection/index.tsx, src/components/organisms/index.ts, src/components/pages/PageTop/index.tsx
- スピーカー、スポンサーを募集するボタンに実際に採用予定のリンクを仕込みました
- その他リファクタリング
refs: https://gophersjp.backlog.com/view/GOCON2023-208
=> feat: add speakers and sponsors link

src/components/atoms/Button/index.tsx, src/components/molecules/SponsorsCard/index.tsx, src/components/organisms/Footer/index.tsx, src/components/organisms/Header/index.tsx, src/components/organisms/SpeakersSection/index.tsx, src/components/organisms/SponsorsSection/index.tsx, src/components/organisms/TopDescription/index.tsx, src/styles/color.ts, src/styles/globals.css, src/styles/theme.ts
全体的にレスポンシブデザインに対応するように調整しました。 Footer のフォントサイズ周りが若干崩れてしまったのですが差分が大きくなりすぎそうなので一旦後回しにしています。
- [fix] Fix the order of `font-family`
- [refactor] Add responsive font sizes etc for variants of Typography
- [feat] Add responsive design for Speakers section
- [refactor] Adjust Button styles
- Footer のリファクタリング
- 個別で fontSize 指定している箇所が多かったので theme で管理したい
- Button の hover 時のスタイル
- なんか sx でいい感じ当てられなかった...
- SpeakersSection のモバイル幅の時の Gopher さんが 320px くらい狭まると応募期間に被る
- なんかいい感じにズラすか諦めるか
- どこまで担保するかにもよるけど個人的には 375px 以下のレイアウト崩れはある程度許容しても良いと思う
https://user-images.githubusercontent.com/40013676/204099473-2fccc92d-937c-41e9-ac22-04e29edf1df2.mov
=> [feat][refactor] Make overall to be responsive

src/components/commons/Layout/index.tsx
デプロイ先ではfavicon(というよりはスマホ向けアイコンか)が404エラーになるので修正
=> fix: favicon link

src/components/organisms/Footer/index.tsx, src/styles/theme.ts
* footerもvariantを見るように修正
* 太いところはh4追加で対応
* なかはbody2で対応
* flexの整理
* `Gopher の原著作者~`の部分は大きすぎると不自然なのと、フォントサイズの制御をする必要がないと判断したのでそのままにしています
* 下のやつに比べて少し大きめになっているので、`subtitle`とかを使って制御した方が良い？
=> footerもvariant使うように修正

src/components/organisms/MainVisual/index.tsx
モバイルで確認したら紙吹雪がはみ出た時に盛大にレイアウトが崩れてたので `overflow: hidden` で対処しました。多分これでなおるはず。
=> [fix] Add `overflow: hidden` to prevent collapsing layout cause of overflowing confetti from viewport

src/components/organisms/SponsorsSection/index.tsx, src/i18n/en.json
「スポンサーを検討する」ボタンのリンクをPDFへのリンクに変更しました。
ついでに英語のラベル「Consider a sponsor」を「Consider sponsoring」に変更しました。
https://user-images.githubusercontent.com/40013676/204576690-3a321cef-6fcf-4083-a6b9-c7a0a7a3cfad.mov
=> [chore] Change link of the button in SponsorsSection to PDF for details of sponsorship plans

src/components/organisms/SpeakersSection/index.tsx, src/i18n/en.json
(軽微なのでセルフマージします)
スピーカー募集セクションの英語を [Slack でご提案いただいた形](https://goconjp.slack.com/archives/C042B8LHA4R/p1669805616372079?thread_ts=1669600500.870169&cid=C042B8LHA4R) に修正しました。
=> [fix] Fix English sentences of Speakers section

src/components/commons/Layout/index.tsx
だめだったらすぐ revert します 🙏 
https://gocon.jp/ で OGP が表示されないので meta タグ追加で動くか確かめたい。
=> [test] Add multiple `og:url`

src/components/commons/Layout/index.tsx
Reverts GoCon/2023#62
だめでした。 gocon.github.io の方に meta タグ設定すればいけるかも?
=> Revert "[test] Add multiple `og:url`"

src/components/commons/Layout/index.tsx
Twitter で表示される OGP のカードでサムネ画像が目立つ感じにする
=> [feat] Add meta tag for `twitter:card` and set content `summary_large_image`

.github/ISSUE_TEMPLATE
Proposal公開に向けてISSUE templateの作成
=> feat: add GitHub template

src/components/organisms/Footer/index.tsx, src/components/organisms/SponsorsSection/index.tsx, src/components/pages/PageTop/index.tsx, src/i18n/en.json, src/i18n/ja.json
- 特商法表記の追加
- スピーカー募集終了に伴う導線削除
日本語
英語
=> feat: specified commercial transaction

package.json, src/components/modals/ModalHeaderMenu/index.tsx, src/components/molecules/HeaderMenu/index.tsx, src/components/organisms/Header/index.tsx, src/components/pages/PageTop/index.tsx, src/i18n/util.ts, src/pages/floor_guide.tsx, src/pages/sessions.tsx, src/pages/timetable.tsx, src/styles/theme.ts, yarn.lock
=> feat: header with link

src/components/pages/PageTop/index.tsx
コミュニティブースの募集は2月で既に締め切っていたのでトップページからリンクを削除する。
PageTop コンポーネントから CommunityBoothSection を削除しました。コンポーネント自体は SpeakersSection と同様にそのまま残っています。
=> chore: Remove CommunityBoothSection from PageTop

src/components/molecules/HeaderMenu/index.tsx, src/components/organisms/Header/index.tsx
4/1 公開に間に合わせるために、ヘッダーのリンクを一時的に Sessionize が構築した HTML ページへの外部リンクに変更する。
- HeaderMenu の `next/link` を削除して a タグで別タブでページ遷移を行うように変更し、TODOコメントを追加
- Header から HeaderMenu にわたす href を Next.js 内のページから Sessionize が構築した HTML ページへのリンクに変更し、TODOコメントを追加
- `/sessions` → https://sessionize.com/api/v2/jmtn42ls/view/Sessions
- `/timetable` → https://sessionize.com/api/v2/jmtn42ls/view/GridSmart
- このままリリースできるようにまだ公開する予定のない floor_guide へのリンクをコメントアウトし、 TODOコメントを追加
画面遷移の様子
https://user-images.githubusercontent.com/40013676/229123987-a6a1fc73-d97c-4ca1-a95c-67f3d773197a.mov
=> chore: Temporarily change links of Header to the links to HTML pages build by Sessionize

src/components/molecules/HeaderMenu/index.tsx, src/components/organisms/Header/index.tsx, src/components/pages/PageTop/index.tsx
一旦この状態のものをmainブランチにマージする想定として、下記の変更を加えると良いかなと思いました
* Sessions, TimeTable, 言語切り替えのいずれも画面遷移を伴わないため、Homeの表示は不要かなと思います
* 余計な通信を行わないため、useSessionizeはコメントアウトします
=> Proposal feat: hide home label from header

.eslintrc.json, src/components/atoms/Button/index.tsx, src/components/atoms/IconTwitter/IconTwitter.stories.tsx, src/components/atoms/IconTwitter/index.tsx, src/components/atoms/Link/index.tsx, src/components/atoms/Logo/index.tsx, src/components/commons/Layout/index.tsx, src/components/molecules/HeaderMenu/index.tsx, src/components/organisms/Footer/FooterBottom.tsx, src/components/organisms/Header/index.tsx, src/components/organisms/SpeakersSection/index.tsx, src/components/pages/PagePartner/index.tsx, src/components/pages/PageTop/index.tsx, src/pages/floor_guide.tsx, src/pages/index.tsx, src/pages/sessions.tsx, src/pages/timetable.tsx
下記の内容が気になったのでeslintの設定ちょっと弄りました
* 使ってない変数の存在が許される
* `import React from 'react'` のおまじないの有無が統一されてない（なくて良いよね）
=> chore: add eslint rule

src/components/organisms/SponsorsSection/index.tsx, src/i18n/en.json, src/i18n/ja.json
すべてのスポンサープランの募集が3/31を以て締め切られたので Web サイトから募集要項へのリンクを削除して文言を修正する。
ref: https://goconjp.slack.com/archives/C042B8LHA4R/p1680324447253439
- `SponsorsSection` のボタンを削除
- `SponsorsSection` の gopher の配置について、ボタンがなくなったことによるズレなどを修正
- `SponsorsSection` の `sponsors_description` (スポンサー募集中です！ / We are looking for sponsors!) を `sponsors_application_closed` (スポンサーの募集は終了いたしました。ホームページへの反映は順次行って参ります。 / Sponsors application has been closed. We will reflect the information on our website in due course.) に変更
=> chore: Close sponsors application

package.json, src/modules/sessionize/hooks.ts, src/modules/sessionize/schema.ts, yarn.lock
Sessionize API へのリクエスト結果を型安全に使用するために [`zod`](https://zod.dev/) を使った schema 定義と `useSessionize` 内での validation を追加しました。
- `yarn add zod`
- `src/modules/sessionize/schema.ts` に Sessionize API の取得結果を元に zod を使った schema オブジェクト (`sessionizeViewAllSchema`) の定義と型 (`SessionizeViewAllSchemaType`) 定義を追加
- `useSessionize` 内でエラーハンドリングと schema validation を追加して、戻り値を `SessionizeViewAllSchemaType | null` に変更
```tsx
import { useSessionize } from 'src/modules/sessionize/hooks'
export const Foo: FC = () => {
const data = useSessionize()
if (!data) {
return <p>Loading...</p>
}
...
}
```
=> feat: Add schema validation for result of Sessionize API

.npmrc, package.json, yarn.lock
`package.json` にて、いくつかの依存関係のバージョンに `^` が付与されていたのを削除して再インストールして `yarn.lock` を更新しました。また、再発防止のために `.npmrc` を作成して `save-exact=true` を設定しました。
ref: https://github.com/GoCon/2023/pull/183#discussion_r1155305041
- chore: Install deps with exact version
- chore: Add a config `save-exact=true` in `.npmrc`
ローカルで適当な deps を yarn add してみて prefix なしのバージョンで追加されたことを確認しました。
=> chore: Fix some deps to with exact version & Add a config `save-exact=true` in `.npmrc`

.git-pr-release, .github/git-pr-release.erb, .github/workflows/create-pr-develop-to-main.yml
`git-pr-release` を使って `develop` から `main` への PR を自動作成するワークフローを追加します。サイト自体に影響はないのでレビューはスキップします。
=> chore: Add a workflow to create PR to main automatically

src/components/organisms/TopDescription/index.tsx
TopDescription のスタイルの余白の指定などに isTabletOrOver を使っている箇所を MUI の media wuery 表記に修正してレイアウトシフトを防ぐようにしました。
=> refactor(TopDescription): No longer using isTabletOrOver for styles to avoid layout shift

src/components/molecules/StaffCard/StaffCard.stories.tsx, src/components/molecules/StaffCard/index.tsx, src/components/organisms/Header/index.tsx, src/components/organisms/StaffCardList/StaffCardList.stories.tsx, src/components/organisms/StaffCardList/index.tsx, src/modules/staff/index.ts, src/pages/staff.tsx
スタッフ一覧ページを作成しました。現時点でフォームに回答のあった順に掲載しています。掲載情報はフリガナを除いて基本的にフォームで回答いただいた通りですが、一部、同じ会社と思われる方の表記がゆれているものは一方に統一しました。
=> feat: Add staff page

src/modules/staff/index.ts
スタッフ一覧ページ `/staff` について、 tottie さんにもご回答いただいたので名前やアイコンなどを追加しました。
=> feat: Add tottie-san's info

next.config.js, package.json
GitHub Pages は `_next` 以下の JS をページとして読み込んでくれないらしい。 `out/` に `.nojekyll` というファイルを作成することでこれを解決できるらしい。
https://qiita.com/ozaki25/items/fe9912fc41c3a5c5bfea#%E3%81%AF%E3%81%BE%E3%82%8A%E3%81%A9%E3%81%93%E3%82%8Djs%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%8C404%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86%E5%95%8F%E9%A1%8C
公式の手順でも入れていた
https://github.com/vercel/next.js/tree/canary/examples/github-pages
=> hotfix: Add touch out/.nojekyll

package.json
build 後に touch しても動かなかったので
ref: [sub-t/blog-template: Next.js + markdown Blog Template](https://github.com/sub-t/blog-template/tree/main)
[Next.js + GitHub Pagesのブログテンプレートを作った](https://zenn.dev/subt/articles/957bd5d01485e1)
=> hotfix: Add .nojekyll to public

src/components/organisms/Header/index.tsx
セッション一覧をはじめとする複数のページがブラウザリロードによって 404 エラーになる問題が発生しているため、解決するまでヘッダーの Sessions のリンクを sessionize がビルドしたページに差し戻します
=> tmp: Revert link to sessions to the page built by sessionize

src/pages/floor_guide.tsx, src/pages/sessions.tsx, src/pages/staff.tsx, src/pages/timetable.tsx
next export実行時に静的HTMLが生成されていなかったので、生成されるようにコードを修正する
=> fix: static site generate

src/modules/staff/index.ts
tenntenn さんの情報を `/staff` に追加しました。
=> feat: Add tenntenn-san's info

src/i18n/en.json, src/i18n/ja.json
トップページのセッションに関する説明を最新の情報に更新しました。
文言についてはセッション班に確認しています 👉  https://goconjp.slack.com/archives/C042B8LHA4R/p1684930102724269
=> chore: Fix sessions count of description in top page

src/components/molecules/StaffCard/index.tsx, src/pages/sessions/[id].tsx
`@mui/icons-material` のアイコンについて、まとめてインポートしているのがビルド時間を長引かせている原因っぽいので path ごとにインポートするように修正しました。
ref: https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports
=> refactor: Use `@mui/icons-material` with path imports to reduce bundle size

src/components/pages/PageSessions/index.tsx
セッション一覧の読み込み中に一瞬薄いグレーの背景の下の方に白い部分が現れるのが気になるので、それを見せないようにしました。
| Before | After |
|--------|--------|
| <a href="https://gyazo.com/97fe877a95e1e25dcf329df1e95497ab"><img src="https://i.gyazo.com/97fe877a95e1e25dcf329df1e95497ab.gif" alt="Image from Gyazo" width="350"/></a> | <a href="https://gyazo.com/ea1317f9d947f094e5afb117988280fb"><img src="https://i.gyazo.com/ea1317f9d947f094e5afb117988280fb.gif" alt="Image from Gyazo" width="350"/></a> |
=> fix: Suppress layout shift after loading in sessions list

src/pages/sessions/[id].tsx
静的ページビルド時の Sessionize API の呼び出しが各ページ毎に発生していたので、２回め以降はキャッシュを利用するようにしてみました。
=> refactor: Reduce build time by caching Sessionize API responses

src/components/molecules/BoothCard/index.tsx
- Floor Guide のページでコミュニティの説明文に含まれるURLをリンクとして機能するようにしました
- 表示用の文字列としては `https://` のプロトコル部分は省略しました
- 文字列の長さが 24 文字を超える部分は `...` として省略するようにしました
| Before | After |
|--------|--------|
| <img src=https://github.com/GoCon/2023/assets/19329/f627a04e-c5f1-440f-9764-9e8a900330d7 width=350> | <img src=https://github.com/GoCon/2023/assets/19329/ecb2e133-88c1-4867-9976-9ba03b53fcb5 width=350> |
=> feat: Replace URLs in floor guide descriptios with links

src/components/molecules/BoothCard/index.tsx, src/modules/util/text.tsx, src/pages/sessions/[id].tsx
- [Floor Guide で実施した](https://github.com/GoCon/2023/pull/254) のと同様の対応をセッション詳細ページにも適用した
- セッション詳細ページは Floor Guide とは異なり表示領域に余裕があるので URL を省略せずにそのまま表示するように対応した
URL を含むセッション詳細ページの例
例1) http://localhost:3000/2023/sessions/A10-S/
例2) http://localhost:3000/2023/sessions/B4-S/
=> feat: Replace URLs with Link in session details

.github/workflows/ci.yml
CI の Post setup Node.js というステップに 2m くらいかかっていたので短縮します。
`actions/setup-node` で yarn のキャッシュをしていたのを止めて、 `actions/cache` で next のキャッシュと同様に node_modules のキャッシュをするように変更し、キャッシュが存在する場合は各種ステップをスキップするように条件文を追加しました。
=> chore: Cache node_modules with `actions/cache` instead of caching with `actions/setup-node`

src/pages/sessions/[id].tsx
Speaker の `bio` に URL を記載しているケースも発見したので対応しました 🙏  (五月雨ですみません 🙇 )
- URLを記載されていた方
- http://localhost:3000/2023/sessions/A11-S/
=> fix: Replace URL string in bio with Link

.github/workflows/ci.yml
gh-pages のアウトプットが全部消えたので next build はスキップしちゃダメそうだった。
=> hotfix: Remove skipping build

.github/workflows/ci.yml
おそらく deps が見つからないことによりビルドが失敗したので、一旦全部の if 分岐をなくして install も lint も実行されるように修正
=> hotfix: Remove skipping all steps

src/components/pages/PageSponsor/index.tsx, src/pages/sessions/[id].tsx
これは https://github.com/GoCon/2023/pull/269 へ向けたPRです。
/sponsors/[plan]/[id] と /sessions/[id] のページタイトルが期待通り反映されるように各ページ内で Meta を呼び出すようにしました。
=> feat: Set meta page title in the pages routed dynamically

src/components/commons/Layout/index.tsx, src/components/pages/PageSponsor/index.tsx, src/pages/sessions/[id].tsx
各ページごとにmeta タグのタイトルを設定します
前年度は (<イベント名 > | <各ページのタイトル>)でしたが、タブが多いと埋もれてしまうので
踏襲せず(<各ページのタイトル>  | <イベント名 >)で行きます
=> feat: change title of meta_tag by pages

src/components/molecules/HeaderMenu/index.tsx, src/components/molecules/PlenumCard/PlenumCard.stories.tsx, src/components/molecules/PlenumCard/index.tsx, src/components/molecules/TimetableRoomHeader/TimetableRoomHeader.stories.tsx, src/components/molecules/TimetableRoomHeader/index.tsx, src/components/molecules/TrackCard/TrackCard.stories.tsx, src/components/molecules/TrackCard/index.tsx, src/components/organisms/Header/index.tsx, src/pages/timetable.tsx
`/timetable` ページを getStaticProps を使って実装しました。関連コンポーネント (TrackCard, PlenumCard) の調整も行っています。スタイルは可能な限りデザインに合わせましたが忠実ではないです。また、モバイル用の調整は本PRでは行っていません。 (モバイル幅になった時のデザインがないのでなんとなく片方のルームだけ表示されて A/B 切り替えボタンみたいなのを置いて切り替えるみたいなイメージをしています。できるかどうかは分からない。もっと良さげなアイディアありましたら教えてください。)
- TrackCard の調整 (スタイルの調整、 props の修正、各セッション詳細ページへのリンク追加)
- PlenumCard の調整 (幅の調整、 minutes prop の追加)
- TimetableRoomHeader の追加 (タイムテーブル上部の Room A/B のヘッダー、スポンサーの許諾が得られ次第イラストアイコンを追加する予定)
- ヘッダーのリンク変更
- `/pages/timetable.tsx` の実装
<details><summary>PC</summary>
</details>
=> feat: Add `/timetable` page with getStaticProps (for PC only)

src/modules/staff/index.ts
yagipy の情報を `/staff` に追加しました。
回答が遅くなってしまったので自分で出しました。
問題なければマージをお願いします。
=> feat: Add yagipy info

src/components/commons/Layout/index.tsx, src/components/pages/PageSponsor/index.tsx, src/pages/sessions/[id].tsx
- `<meta property="og:title" />` にタイトルを設定しました
- SNS でシェアしたときに、セッション名やスポンサー名が表示されることを期待して設定しています
- 基本的に `<title>` 要素と同じ内容を出すようにしています
- 参考: https://nextjs.org/docs/pages/api-reference/components/head
(スポンサーページ)
```html
<meta property="og:title" content="株式会社カンム | Go Conference 2023">
```
(セッションページ)
```html
<meta property="og:title" content="タクシーアプリ『GO』高速マッチングシステムで実践したGoチューニングテクニック | Go Conference 2023">
```
=> fix: Set og:title tag

src/components/commons/Layout/index.tsx, src/components/pages/PageSponsor/index.tsx, src/pages/sessions/[id].tsx
og:site_name にもサイト名が入っていて冗長なので og:title からはサイト名を取り除く.
(Before)
```html
<meta property="og:title" content="タクシーアプリ『GO』高速マッチングシステムで実践したGoチューニングテクニック | Go Conference 2023">
```
(After)
```html
<meta property="og:title" content="タクシーアプリ『GO』高速マッチングシステムで実践したGoチューニングテクニック">
```
=> fix: Remove site name from og:title
